# bundle exec jekyll serve --watch

# Site settings
title: "Scholars’ Lab"
name: "Scholars’ Lab"
email: scholarslab@virginia.edu
description: "The Scholars’ Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maybe.scholarslab.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scholarslab
permalink: /:year/:month/:day/:title/

# Build settings
analytics: false
incremental: true
sass:
  sass_dir: assets/css/_sass
  style: expanded # temporary! change back to compressed later
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs
  - node_modules
  - theme-testing
#  - _posts # temporary! significantly reduces build time for theme testing
  - assets/python # helper scripts to manipulate HTML/CSS, not used in build
collections:
  people:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/
  lab:
    output: true
    permalink: /:collection/:name/
  starter-kits:
    output: true
    permalink: /:collection/:name/
  events:
    output: true
    permalink: /:collection/:name/
  todo:
    output: true
    permalink: /:collection/:name/
  fake-blog:
    output: true
    permalink: /:year/:month/:day/:title/
  fake-people:
    output: true
    permalink: /:collection/:name/

header_pages:
  - about.md
  - people.md
  - blog.md
  - research.md
  - lab.md
  - search.html

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      order: 10
